spring:
  application:
    name: hystrix-terbine-server
server:
  port: 8778
security:
  basic:
    enabled: false
turbine:
  aggregator:
    clusterConfig: default
  appConfig: eshop-one-service
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@192.168.56.122:8761/eureka/